// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdSt1LUPnJzjy8jlWFpxSOVca3EnEjOFg',
    appId: '1:852326781913:web:ee122b649c268415b77fc8',
    messagingSenderId: '852326781913',
    projectId: 'quark-3b74e',
    authDomain: 'quark-3b74e.firebaseapp.com',
    storageBucket: 'quark-3b74e.firebasestorage.app',
    measurementId: 'G-B3QD50TN7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjKIdTLdqwoao1BPzrV1pQBPXrcBhX4s',
    appId: '1:852326781913:android:1c5e62dbbd9bee78b77fc8',
    messagingSenderId: '852326781913',
    projectId: 'quark-3b74e',
    storageBucket: 'quark-3b74e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJgylszspvoyq5cvHfdso5NZyrB_HVTc',
    appId: '1:852326781913:ios:4c821a3d483dffb3b77fc8',
    messagingSenderId: '852326781913',
    projectId: 'quark-3b74e',
    storageBucket: 'quark-3b74e.firebasestorage.app',
    iosBundleId: 'com.example.superx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJgylszspvoyq5cvHfdso5NZyrB_HVTc',
    appId: '1:852326781913:ios:4c821a3d483dffb3b77fc8',
    messagingSenderId: '852326781913',
    projectId: 'quark-3b74e',
    storageBucket: 'quark-3b74e.firebasestorage.app',
    iosBundleId: 'com.example.superx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdSt1LUPnJzjy8jlWFpxSOVca3EnEjOFg',
    appId: '1:852326781913:web:d4044a16c0af22e4b77fc8',
    messagingSenderId: '852326781913',
    projectId: 'quark-3b74e',
    authDomain: 'quark-3b74e.firebaseapp.com',
    storageBucket: 'quark-3b74e.firebasestorage.app',
    measurementId: 'G-K9HFY3FQS4',
  );
}
